name: pipeline ci/cd - publish federation package

on:
  workflow_call:
    inputs:
      working_directory:
        description: project directory to restore/build/pack
        required: true
        type: string

      dotnet_version:
        description: .NET SDK version
        required: false
        type: string
        default: 9.0.x

      base_version:
        description: base semantic version
        required: false
        type: string
        default: "1.0"

      publish_package:
        description: if false, runs restore/build/pack without pushing
        required: false
        type: boolean
        default: true
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: restore dependencies
        run: dotnet restore

      - name: build
        run: dotnet build --configuration Release --no-restore

      - name: test
        run: dotnet test --configuration Release --no-restore --no-build

      - name: set version and pack
        id: pack
        env:
          BASE_VERSION: ${{ inputs.base_version }}
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
            VERSION="${BASE_VERSION}.${GITHUB_RUN_NUMBER}"
          else
            VERSION="${BASE_VERSION}-beta.${GITHUB_RUN_NUMBER}"
          fi

          echo "use version: $VERSION"
          dotnet pack -c Release -p:PackageVersion=$VERSION -o ./output --no-build

          echo "package_version=$VERSION" >> $GITHUB_OUTPUT

      - name: push package to nuget
        if: ${{ inputs.publish_package }}
        run: dotnet nuget push ./output/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
